# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ff3f2bceacf7a82e548f03d2dd649be1ab26e8cb9d7d3b13aef039e94608dfea1cc6050bf071d9f01b1c43430c13942bff28bf4aae0d2a2c972730fafa7bb82
  imgur:
    client_id: 85a5f4ec8edb130
    client_secret: 859c32ed1cec6d5cf30f9be6a0493b1168499585
    access_token: 3982b61086bc0ff738a2c41eaa23f2758091d621
    refresh_token: 4ebc09657abeb8c4490d80af77a7e79f7d10b2fa
  beacon_providers:
    estimote:
      app_id: simple-beacon-cms-5yb
      app_token: d308f21d475bd7d97c1b777d05494f92
    kontakt:
      api_key: UitaaSXHEaULeuDXBofYLTFnBRNFetpo

test:
  secret_key_base: b1f06355b312189f364361bf05211c061b36448c2f94a7629d5eba8b6d577eedf8b094861687b78ee052e80a30fe8390758d170c91b8f7cf2d9d1828872ab05a
  imgur:
      client_id: 85a5f4ec8edb130
      client_secret: 859c32ed1cec6d5cf30f9be6a0493b1168499585
      access_token: 3982b61086bc0ff738a2c41eaa23f2758091d621
      refresh_token: 4ebc09657abeb8c4490d80af77a7e79f7d10b2fa
  beacon_providers:
    estimote:
      app_id: simple-beacon-cms-5yb
      app_token: d308f21d475bd7d97c1b777d05494f92
    kontakt:
      api_key: UitaaSXHEaULeuDXBofYLTFnBRNFetpo

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  imgur:
      client_id: <%= ENV["IMGUR_CLIENT_ID"] %>
      client_secret: <%= ENV["IMGUR_CLIENT_SECRET"] %>
      access_token: <%= ENV["IMGUR_ACCESS_TOKEN"] %>
      refresh_token: <%= ENV["IMGUR_REFRESH_TOKEN"] %>
  beacon_providers:
    estimote:
      app_id: <%= ENV["ESTIMOTE_CLOUD_APP_ID"] %>
      app_token: <%= ENV["ESTIMOTE_CLOUD_APP_TOKEN"] %>
    kontakt:
      api_key: <%= ENV["KONTAKT_API_KEY"] %>